### PR TITLE
Use verification button instead of command with `modals` for verification

### PR DESCRIPTION
**Pull request by Arikatsu**
### What's in the pr
1. Bump discord.js version to `13.7.0` to support modals
2. Add modal for verification
3. Update Verification Messages

**Note: the hash for the password is still for the old password `sponzen`. Adjust it as you want.**

**Using `verify` command will now show the verification modal where users can input the verification password**

image
image
image

### CODE REVIEW

**Comment by Arikatsu** [comment]
ayoo

**Comment by lilmayofuksu** [comment]
omg scald

**Comment by Arikatsu** [comment]
omg ayy lmao

**Comment by TukanDev** [comment]
omg scald you should have made a button to open a modal but still you are hot

**Comment by Arikatsu** [comment]
Sob

**Comment by alt3ri** [comment]
password leaked

**Review by memetrollsXD — CHANGES_REQUESTED** [review]
Instead of a slash command, is it possible to replace it with a message with a button? Then there's no way someone has a skill issue with slash commands

Also, pls fix merge conflicts

**Comment by Arikatsu** [comment]
alr sure

**Comment by Arikatsu** [comment]
There you go
image

**Will now require new translations for verification messages**

**Review by memetrollsXD — APPROVED** [review]

**Comment by memetrollsXD** [comment]
I don't think that will be a big issue, since it's a big green button and the only interactive thing

**Pull request merged**
