### PR TITLE
actual sloot command

### PR DESCRIPTION
**Pull request by Arikatsu**
it works this time i swear i tested 😭😭😭

### CODE REVIEW

**Review by KingRainbow44 — CHANGES_REQUESTED** [review]
please add `db/sloot.json` to your `.gitignore`

**Comment by KingRainbow44** [comment]
> please add `db/sloot.json` to your `.gitignore`

actually forget this
it seems like meme essentially everything pushed

**Review by KingRainbow44 — APPROVED** [review]

**Comment by Arikatsu** [comment]
uwu

**Comment by KingRainbow44** [comment]
suggestion: sub command to randomly pick an image
tbh i can prob do this myself

**Comment by KingRainbow44** [comment]
random sloot works but idk if the `${process.cwd()}/src/db/sloot.json` statement will mess it up
i had to use `process.cwd()` instead of `../db/sloot.json` in my case but it might not be needed on production

**Comment by memetrollsXD** [comment]
bro wtf

**Comment by memetrollsXD** [comment]
are you ok

**Comment by KingRainbow44** [comment]
sorry for reverting your `import` change to `require` lmao

**Comment by memetrollsXD** [comment]
process.cwd()???

**Comment by KingRainbow44** [comment]
yes i use `cwd` dont judge me

**Comment by memetrollsXD** [comment]
you know there's __dirname right

**Comment by KingRainbow44** [comment]
yea but i didnt think of that so i used cwd

**Comment by KingRainbow44** [comment]
there u happy

**Comment by Arikatsu** [comment]
lmfao chaos happened while i slept

**Pull request merged**
