### PR TITLE
remove pls tysm

### PR DESCRIPTION
**Pull request by KiminaNatsuki**
or i will cancel you(real)

### CODE REVIEW

**Review by KingRainbow44 — CHANGES_REQUESTED** [review]
please pick a random image from a collection and reply instead of deleting thx

**Comment by KiminaNatsuki** [comment]
> please pick a random image from a collection and reply instead of deleting thx

fuck you :sob:

**Review by memetrollsXD — CHANGES_REQUESTED** [review]
Hi @Kimi898246!

Thank you for contributing to lawnmower. Before I merge your pull request, I have some changes I’d like you to make.

1. Please add a function to remove the slash command as well. Removing the handler doesn’t remove the slash command as well

If you made these changes, please request a review from me again!

Regards,
memetrollsXD

**Comment by memetrollsXD** [comment]
Alternatively, you can repurpose this command handler to pick a random image from a collection and reply. I think this would make a great addition to the community 😋

**Comment by nitrog0d** [comment]
balls in my

**Comment by nitrog0d** [comment]
image

**Pull request closed without merging**
