### PR TITLE
Add 🔨 again and stop the process from crashing

### PR DESCRIPTION
**Pull request by nitrog0d**
Didn't test, can't test
trust it worky

### CODE REVIEW

**Comment by KiminaNatsuki** [comment]
nice

**Comment by 4Benj** [comment]
> stop the process from crashing

Why would you ever want to stop the process from crashing?

**Comment by KiminaNatsuki** [comment]
> > stop the process from crashing
> 
> Why would you ever want to stop the process from crashing?

why not

**Comment by nitrog0d** [comment]
to stop the downtime
bandaged fix until meme finds the actual problem if it wasn't the .delete()

**Comment by memetrollsXD** [comment]
Stopping the process from crashing can get.. wonky..

> Note that uncaughtException is a very crude mechanism for exception
handling and may be removed in the future

> Don't use uncaughtException, use domains with clusterinstead. If you do
use uncaughtException, restart your application after every unhandled
exception!

**Comment by nitrog0d** [comment]
not in that case, it's just a discord api error
you can try ignoring the whole catch unhandled exceptions/promises and see what the .catch() does after the .delete() if ur that worried about it
yes it's a bandaged fix but apparently you don't want to go there and find the issue, you even suggested switching libs 🤡

**Pull request merged**
